--liquibase formatted sql

--changeset inventory service:1

DROP TABLE IF EXISTS LIQUIBASE_DEMO;

CREATE TABLE LIQUIBASE_DEMO (
  ID BIGINT NOT NULL AUTO_INCREMENT  PRIMARY KEY COMMENT 'id',
  NAME VARCHAR(100) NOT NULL DEFAULT 'UNKNOWN' COMMENT '名字',
  PATH VARCHAR (200) COMMENT '地址'
);